# Generated by Django 3.0.3 on 2020-02-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dataset',
            field=models.FileField(upload_to='datasets/'),
        ),
    ]
