# Generated by Django 2.2.5 on 2020-02-20 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20200220_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dataset',
            new_name='Datasets',
        ),
        migrations.RenameModel(
            old_name='project',
            new_name='Projects',
        ),
    ]
