# Generated by Django 2.2.5 on 2020-02-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200220_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dataset',
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset',
            field=models.FileField(default='', upload_to='datasets/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
