# Generated by Django 3.0.3 on 2020-05-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='size',
        ),
        migrations.AlterField(
            model_name='plot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
