# Generated by Django 3.0.3 on 2020-05-01 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200501_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
