# Generated by Django 3.0.3 on 2020-05-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_plot_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='plottype',
            field=models.CharField(default='Single', max_length=100),
            preserve_default=False,
        ),
    ]
