# Generated by Django 3.0.7 on 2020-06-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_plot_plottype'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
